name: Build MusicSlot Mod

# Controls when the action will run. 
on:
  # This workflow runs when a push to 1.4 or main branches happens
  push:
    branches: [1.4, main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Make sure only to on push events. Can add other specific checks here
    if: github.event_name == 'push'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out base branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # GitHub runners may have outdated .NET versions.
      - name: Install .NET SDKs
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      # Runs a set of commands using the runners shell
      - name: Build script
        shell: bash
        run: |
          echo ::group::Installing Steam
          echo Attempting Install of Steam
          #"${{ github.workspace }}"/CIBuildTool/Steam/SteamSetup.exe /S
          echo ::endgroup::
          
          changeNotes=help
          
          ciToolDir="${{ github.workspace }}"/CIBuildTool
          cd $ciToolDir
          
          echo ::group::Fetching tModLoader
          echo off
          #steamcmd +login "${{ secrets.STEAM_USERNAME }}" "${{ secrets.STEAM_PASSWORD }}" +force_install_dir tMod "+app_update 1281930 -validate -beta public-1.4-alpha" +quit 
          echo on
          echo ::endgroup::
          
          echo ::group::Building Mod         
          cd $ciToolDir/tMod
          dotnet tmodloader.dll -server -build "${{ github.workspace }}" -tmlsavedirectory $ciToolDir -ciprep $changeNotes
          cd ..
          echo ::endgroup::
          
          echo ::group::Publishing Mod
          rm -r -f CIBuildTool/tMod
          mkdir -p artifacts/Release
          cp -r CIBuildTool/. artifacts/Release
          
          #steamcmd +login %username% +workshop_build_item publish.vdf +quit
          
          echo ::endgroup::
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Release Build
          path: |
            "${{ github.workspace }}"/artifacts/Release
            
 